# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-stack" do
  version "4.0.0"

  on_macos do
    on_intel do
      sha256 "307b1d64e8ed019afbbe1560395fa09f6aaabeb57ddd53e58db99553ec0fb8bf"
      url "https://github.com/israelmalagutti/git-stack/releases/download/v#{version}/gs-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "d744f1df48aba04854ca516ead1bd148559182ad470b6f051ca614a231d3ba93"
      url "https://github.com/israelmalagutti/git-stack/releases/download/v#{version}/gs-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e6f3c728d5e367699041afeecb4e56797718d04065d42df04069223f7e41c2d8"
      url "https://github.com/israelmalagutti/git-stack/releases/download/v#{version}/gs-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "13691a2ec08ac809bd02db1a9546538e422a3a042d8643f31ceadfc41ea12f9b"
      url "https://github.com/israelmalagutti/git-stack/releases/download/v#{version}/gs-linux-arm64.tar.gz"
    end
  end

  name "git-stack"
  desc "CLI tool for managing stacked branches in git"
  homepage "https://github.com/israelmalagutti/git-stack"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-stack"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gs"]
    end
  end

  # No zap stanza required

end
