# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-stack" do
  version "0.11.1"

  on_macos do
    on_intel do
      url "https://github.com/israelmalagutti/git-stack/releases/download/v#{version}/gs-darwin-amd64.tar.gz"
      sha256 "5f066e9406f1915bcd27aad9a990d7771ef4d819a8a416c02bf278330c6b2eea"
    end
    on_arm do
      url "https://github.com/israelmalagutti/git-stack/releases/download/v#{version}/gs-darwin-arm64.tar.gz"
      sha256 "27838d8f2bbbf9f7d1dec670cac91a61aac4087523037a6c8c45ab6f2d1ca8fb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/israelmalagutti/git-stack/releases/download/v#{version}/gs-linux-amd64.tar.gz"
      sha256 "1f15c461084cbf85f8ac8a08558c1a9d3cced43119d2daefe6256588a97fbac5"
    end
    on_arm do
      url "https://github.com/israelmalagutti/git-stack/releases/download/v#{version}/gs-linux-arm64.tar.gz"
      sha256 "8ee130a9d966e505b2948801289c35b6ee2bee13deaaa4f3e2dc46a05d17fb9e"
    end
  end

  name "git-stack"
  desc "CLI tool for managing stacked branches in git"
  homepage "https://github.com/israelmalagutti/git-stack"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-stack"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gs"]
    end
  end

  # No zap stanza required

end
