# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-stack" do
  version "0.12.0"

  on_macos do
    on_intel do
      url "https://github.com/israelmalagutti/git-stack/releases/download/v#{version}/gs-darwin-amd64.tar.gz"
      sha256 "80aecab9ea1d3aa683f9f5827b773a7c0b8fdcbd5da9af936496ee4f5d722d31"
    end
    on_arm do
      url "https://github.com/israelmalagutti/git-stack/releases/download/v#{version}/gs-darwin-arm64.tar.gz"
      sha256 "67e2067b8b4360ab28c659917adc72632ab135a52a0d0ee92674c6c42c764034"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/israelmalagutti/git-stack/releases/download/v#{version}/gs-linux-amd64.tar.gz"
      sha256 "94e943961d3fb9ce9ff9391ae322f7d1e8bca0e457f1a712f6bc940bcbe62f96"
    end
    on_arm do
      url "https://github.com/israelmalagutti/git-stack/releases/download/v#{version}/gs-linux-arm64.tar.gz"
      sha256 "e90d2717fe5c00e42de30e3f48ab28ec82a481d07f7da7f50bd0951188e22dc0"
    end
  end

  name "git-stack"
  desc "CLI tool for managing stacked branches in git"
  homepage "https://github.com/israelmalagutti/git-stack"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-stack"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gs"]
    end
  end

  # No zap stanza required

end
