# This file was generated by GoReleaser. DO NOT EDIT.
cask "gs" do
  name "gs"
  desc "CLI tool for managing stacked branches in git"
  homepage "https://github.com/israelmalagutti/git-stack"
  version "0.11.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gs"

  on_macos do
    on_intel do
      url "https://github.com/israelmalagutti/git-stack/releases/download/v#{version}/gs-darwin-amd64.tar.gz"
      sha256 "8f940f7db76fbe781b8c88e59d89bac646b3749715aa2e9026e9dd60ae8221c9"
    end
    on_arm do
      url "https://github.com/israelmalagutti/git-stack/releases/download/v#{version}/gs-darwin-arm64.tar.gz"
      sha256 "ce76286aa7e15abd71dc5fa5b5f7eb5ab1b09382149494bdc8c360894493c59f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/israelmalagutti/git-stack/releases/download/v#{version}/gs-linux-amd64.tar.gz"
      sha256 "f982178b56239dbd8e5d8c94682116eb17c3fd3ae2283276ea47b81a93f100dd"
    end
    on_arm do
      url "https://github.com/israelmalagutti/git-stack/releases/download/v#{version}/gs-linux-arm64.tar.gz"
      sha256 "8249b75c07324e6a97ea3e2f12921900ec2728a635b489921605a29b6a1309bd"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gs"]
    end
  end

  # No zap stanza required
end
